### ISSUE TITLE
绑定sk之后输入刷新ck没有反馈

### ISSUE THREAD

**Issue by Feilx234** [ctrlcvs/xiaoyao-cvs-plugin#105]
yunzai v3装了miaomiao

以下是日志

|Yunzai-Bot  | [YzBot][11:12:03.746][INFO] recv from: [Private: 1143072920(friend)] #刷新ck
0|Yunzai-Bot  | [YzBot][11:12:04.308][MARK] [xiaoyao-cvs-plugin][dispatch] 检查cookie正常 [uid:101609251]
0|Yunzai-Bot  | [YzBot][11:12:04.335][MARK] [xiaoyao-cvs-plugin][dispatch] 保存cookie成功 [uid:101609251] [ltuid:28985562]
0|Yunzai-Bot  | [YzBot][11:12:04.874][MARK] [xiaoyao-cvs-plugin][dispatch] 检查cookie正常 [uid:101609251]
0|Yunzai-Bot  | [YzBot][11:12:04.884][MARK] [xiaoyao-cvs-plugin][dispatch] 保存cookie成功 [uid:101609251] [ltuid:28985562]
0|Yunzai-Bot  | [YzBot][11:12:05.301][ERRO] [xiaoyao-cvs-plugin][dispatch]
0|Yunzai-Bot  | [YzBot][11:12:05.302][ERRO] Error: connect EINVAL 0.0.0.1:443 - Local (0.0.0.0:0)
0|Yunzai-Bot  |     at Function.AxiosError.from (/root/yunzai/node_modules/.pnpm/registry.npmmirror.com+axios@1.4.0/node_modules/axios/dist/node/axios.cjs:836:14)
0|Yunzai-Bot  |     at RedirectableRequest.handleRequestError (/root/yunzai/node_modules/.pnpm/registry.npmmirror.com+axios@1.4.0/node_modules/axios/dist/node/axios.cjs:3010:25)
0|Yunzai-Bot  |     at RedirectableRequest.emit (node:events:390:28)
0|Yunzai-Bot  |     at ClientRequest.eventHandlers.<computed> (/root/yunzai/node_modules/.pnpm/registry.npmmirror.com+follow-redirects@1.15.2_debug@4.3.4/node_modules/follow-redirects/index.js:14:24)
0|Yunzai-Bot  |     at ClientRequest.emit (node:events:390:28)
0|Yunzai-Bot  |     at TLSSocket.socketErrorListener (node:_http_client:447:9)
0|Yunzai-Bot  |     at TLSSocket.emit (node:events:390:28)
0|Yunzai-Bot  |     at emitErrorNT (node:internal/streams/destroy:157:8)
0|Yunzai-Bot  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
0|Yunzai-Bot  |     at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by Feilx234** [comment]
还遇到一个问题是 五星圣遗物图鉴 给出的列表里面没有更新新的圣遗物名称
