### ISSUE TITLE
Windows 下获取图片路径错误，无法发送图片

### ISSUE THREAD

**Issue by beilove** [ctrlcvs/xiaoyao-cvs-plugin#129]
系统：Windows11 专业版 22H2  22621.2428
机器人框架：喵崽 3.1.3 ws连接ntQQ
描述：在使用图鉴类命令时，无法发出图片，报错里显示路径出错了应该，我并未修改过插件
报错：
[12:23:00.639][ERRO] 发送消息错误:{"type":"image","file":"file://C:\\beichen\\Miao-Yunzai/plugins/xiaoyao-cvs-plugin/resources/xiaoyao-plus/wuqi_tujian/若水.png"}
[12:23:00.639][ERRO] Error: ENOENT: no such file or directory, open 'file://C:\beichen\Miao-Yunzai/plugins/xiaoyao-cvs-plugin/resources/xiaoyao-plus/wuqi_tujian/若水.png'
    at Object.openSync (node:fs:601:3)
    at Object.readFileSync (node:fs:469:35)
    at upload (file:///C:/beichen/Miao-Yunzai/plugins/ws-plugin/model/red/tool.js:62:21)
    at uploadImg (file:///C:/beichen/Miao-Yunzai/plugins/ws-plugin/model/red/tool.js:26:24)
    at makeSendMsg (file:///C:/beichen/Miao-Yunzai/plugins/ws-plugin/model/red/message.js:33:27)
    at QQRedBot.sendPrivateMsg (file:///C:/beichen/Miao-Yunzai/plugins/ws-plugin/model/red/bot.js:155:79)
    at Object.sendMsg (file:///C:/beichen/Miao-Yunzai/plugins/ws-plugin/model/red/bot.js:79:46)
    at e.reply [as replyNew] (file:///C:/beichen/Miao-Yunzai/plugins/ws-plugin/model/red/message.js:448:37)
    at e.reply (file:///C:/beichen/Miao-Yunzai/lib/plugins/loader.js:532:28)
    at filePath (file:///C:/beichen/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/apps/xiaoyao_image.js:132:6)
    at Module.AtlasAlias (file:///C:/beichen/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/apps/xiaoyao_image.js:31:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async atlas.dispatch (file:///C:/beichen/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/adapter/index.js:47:19)
    at async PluginsLoader.deal (file:///C:/beichen/Miao-Yunzai/lib/plugins/loader.js:291:54) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'file://C:\\beichen\\Miao-Yunzai/plugins/xiaoyao-cvs-plugin/resources/xiaoyao-plus/wuqi_tujian/若水.png'
}

**Comment by 1055169799** [comment]
现在还报错吗？看看拓展包有没有下载，就是resources里有没有xiaoyao-plus这个文件夹。然后检查一下文件夹是否命名错误

**Comment by beilove** [comment]
> 现在还报错吗？看看拓展包有没有下载，就是resources里有没有xiaoyao-plus这个文件夹。然后检查一下文件夹是否命名错误

现在是好了，之前检查过文件夹，文件都是在的，就很奇怪
