### ISSUE TITLE
原神国际服绑不了ck

### ISSUE THREAD

**Issue by BeggingHorse** [ctrlcvs/xiaoyao-cvs-plugin#146]
[15:38:30.596][ERRO] [xiaoyao-cvs-plugin][dispatch]
[15:38:30.709][ERRO] TypeError: HttpsProxyAgent is not a constructor
    at miHoYoApi.getAgent (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/model/mys/mihoyoApi.js:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async miHoYoApi.getData (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/model/mys/mihoyoApi.js:86:11)
    at async user.getData (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/model/user.js:82:19)
    at async Module.bindLogin_ticket (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/apps/user.js:235:13)
    at async atlas.dispatch (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/adapter/index.js:47:19)
    at async PluginsLoader.deal (file:///C:/Users/Administrator/Desktop/Miao-Yunzai/lib/plugins/loader.js:269:41)
    
    [HoYoverse通行证]获取cookie_token成功，下面开始执行官方绑定过程。。。

**Comment by iedhgherljhfloj** [comment]
试试 https://github.com/ctrlcvs/xiaoyao-cvs-plugin/pull/138/files

**Comment by BeggingHorse** [comment]
> 试试 https://github.com/ctrlcvs/xiaoyao-cvs-plugin/pull/138/files

好使！谢谢佬
