### ISSUE TITLE
[ERRO] TypeError: Bot.logger.blue is not a function

### ISSUE THREAD

**Issue by CUZNIL** [ctrlcvs/xiaoyao-cvs-plugin#59]
![VGA@7~$9 TF3T`3{FS3LP(Y](https://user-images.githubusercontent.com/76582404/226843414-3d48a0ef-d36a-49ed-be35-d99c35f54fdc.jpg)

如图所示，#扫码登录 会报错。

```
[YzBot][16:14:06.172][ERRO] [xiaoyao-cvs-plugin][dispatch]
[YzBot][16:14:06.173][ERRO] TypeError: Bot.logger.blue is not a function
at mysTopLogin.GetQrCode (file:///root/TRSS_Yunzai/Yunzai/plugins/xiaoyao-cvs-plugin/model/mhyTopUpLogin.js:47:55)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Module.qrCodeLogin (file:///root/TRSS_Yunzai/Yunzai/plugins/xiaoyao-cvs-plugin/apps/mhyTopUpLogin.js:63:8)
at async atlas.dispatch (file:///root/TRSS_Yunzai/Yunzai/plugins/xiaoyao-cvs-plugin/adapter/index.js:47:19)
at async PluginsLoader.deal (file:///root/TRSS_Yunzai/Yunzai/lib/plugins/loader.js:255:52)
```

**Comment by CUZNIL** [comment]
https://github.com/ctrlcvs/xiaoyao-cvs-plugin/pull/60 似乎是后续维护改动导致的主体不支持，如有遇到可以尝试参考此pr手动更改。
