### ISSUE TITLE
#更新抽卡记录报错

### ISSUE THREAD

**Issue by RSRH-Rs** [ctrlcvs/xiaoyao-cvs-plugin#87]
获取完了之后报错
![image](https://github.com/ctrlcvs/xiaoyao-cvs-plugin/assets/54684882/ba9250f3-5f4b-4d15-afda-1483afa3a07f)

**Comment by JFM6266** [comment]
我也几乎遇到相同的问题

[MiaoYz][02:31:43.308][ERRO] [xiaoyao-cvs-plugin][dispatch]                                   
[MiaoYz][02:31:43.309][ERRO] Error: connect EINVAL 0.0.0.1:443 - Local (0.0.0.0:0)            
    at AxiosError.from (/root/TRSS_Yunzai/Miao-Yunzai/node_modules/.pnpm/axios@1.4.0/node_modules/axios/dist/node/axios.cjs:836:14)                                                         
    at RedirectableRequest.handleRequestError (/root/TRSS_Yunzai/Miao-Yunzai/node_modules/.pnpm/axios@1.4.0/node_modules/axios/dist/node/axios.cjs:3010:25)                                 
    at RedirectableRequest.emit (node:events:511:28)                                          
    at eventHandlers.<computed> (/root/TRSS_Yunzai/Miao-Yunzai/node_modules/.pnpm/follow-redirects@1.15.2_debug@4.3.4/node_modules/follow-redirects/index.js:14:24)                         
    at ClientRequest.emit (node:events:511:28)                                                
    at TLSSocket.socketErrorListener (node:_http_client:495:9)                                
    at TLSSocket.emit (node:events:511:28)                                                    
    at emitErrorNT (node:internal/streams/destroy:151:8)                                      
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)                                 
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
